import type { DiscoverItem, Person, StatusMeta, Title } from "./types";

export const CREW: Person[] = [
  {
    id: "jero",
    name: "Jero",
    short: "Jero",
    initial: "J",
    color: "#f0604a",
    colorSoft: "#c9432f",
    tint: "rgba(240,96,74,.16)",
    tag: "Última: The Glory · ep 6",
    streak: "4 semanas seguidas",
  },
  {
    id: "flor",
    name: "Flor",
    short: "Flor",
    initial: "F",
    color: "#e2a44b",
    colorSoft: "#b07d2f",
    tint: "rgba(226,164,75,.16)",
    tag: "Última: Hometown Cha-Cha-Cha · ep 10",
    streak: "2 semanas seguidas",
  },
  {
    id: "liz",
    name: "Liz",
    short: "Liz",
    initial: "L",
    color: "#d6849b",
    colorSoft: "#a75f74",
    tint: "rgba(214,132,155,.16)",
    tag: "Última: Reply 1988 · terminada",
    streak: "6 semanas seguidas",
  },
];

export const MONTHS = ["Abr", "May", "Jun", "Jul", "Ago", "Sep"];

export const ACTIVITY: Record<string, number[]> = {
  jero: [2, 3, 1, 4, 2, 3],
  flor: [1, 1, 2, 2, 3, 1],
  liz: [3, 2, 4, 3, 4, 2],
};

export const TITLES: Title[] = [
  {
    id: "cly",
    title: "Crash Landing on You",
    orig: "사랑의 불시착",
    year: 2019,
    kind: "Serie",
    ep: 16,
    epTotal: 16,
    platform: "Netflix",
    tags: ["Romance", "Comedia"],
    status: "visto",
    synopsis:
      "Una heredera surcoreana aterriza en paracaídas del lado equivocado de la frontera y un capitán norcoreano decide esconderla. Sí, otra vez esa escena del piano.",
    critic: { score: "8.7", quote: "Melodrama de manual ejecutado con una precisión que desarma" },
    ratings: { jero: 9, flor: 10, liz: 8 },
    comments: {
      jero: "Los últimos dos episodios me arruinaron una semana laboral entera.",
      flor: "Perfecta. No acepto debate ni preguntas.",
      liz: "Muy larga la subtrama de los vecinos, igual la banda sonora salva todo.",
    },
    when: { jero: "hace 3 sem", flor: "hace 3 sem", liz: "hace 1 mes" },
  },
  {
    id: "r1988",
    title: "Reply 1988",
    orig: "응답하라 1988",
    year: 2015,
    kind: "Serie",
    ep: 20,
    epTotal: 20,
    platform: "Netflix",
    tags: ["Familia", "Nostalgia"],
    status: "visto",
    synopsis:
      "Cinco familias en un callejón de Seúl en el año 88. No pasa casi nada y a la vez pasa absolutamente todo.",
    critic: { score: "9.2", quote: "La mejor serie coreana sobre vivir al lado de otra gente" },
    ratings: { jero: 10, flor: 9, liz: 10 },
    comments: {
      jero: "Cada vez que la recomiendo pierdo un amigo por dos semanas.",
      flor: "El triángulo amoroso es un crimen, el resto es oro.",
      liz: "La vi tres veces. Voy por la cuarta.",
    },
    when: { jero: "hace 2 meses", flor: "hace 2 meses", liz: "hace 5 días" },
  },
  {
    id: "glory",
    title: "The Glory",
    orig: "더 글로리",
    year: 2022,
    kind: "Serie",
    ep: 6,
    epTotal: 16,
    platform: "Netflix",
    tags: ["Thriller", "Venganza"],
    status: "mirando",
    synopsis:
      "Una mujer construye durante veinte años la venganza más paciente de la televisión coreana. El tablero de go es literal.",
    critic: { score: "8.4", quote: "Fría, milimétrica y con una Song Hye-kyo irreconocible" },
    ratings: { jero: 8, flor: 0, liz: 9 },
    comments: {
      jero: "Voy por el 6 y ya no puedo mirar un tablero de go igual.",
      flor: "Arranco el finde, no me cuenten nada.",
      liz: "Terminada en dos noches. Obra maestra del rencor.",
    },
    when: { jero: "ayer", flor: "—", liz: "hace 1 sem" },
  },
  {
    id: "mymister",
    title: "My Mister",
    orig: "나의 아저씨",
    year: 2018,
    kind: "Serie",
    ep: 0,
    epTotal: 16,
    platform: "Viki",
    tags: ["Drama", "Vida"],
    status: "pendiente",
    synopsis:
      "Un ingeniero cansado y una joven con demasiadas deudas encuentran algo parecido a la decencia. Lenta, gris, enorme.",
    critic: { score: "9.0", quote: "Un estudio sobre la bondad hecho sin una sola concesión" },
    ratings: { jero: 0, flor: 0, liz: 0 },
    comments: {
      jero: "Me dijeron que hay que verla con pañuelos y tiempo libre.",
      flor: "La sumé yo. Alguien acompáñeme.",
      liz: "Pendiente eterna.",
    },
    when: { jero: "—", flor: "—", liz: "—" },
  },
  {
    id: "goblin",
    title: "Goblin",
    orig: "도깨비",
    year: 2016,
    kind: "Serie",
    ep: 16,
    epTotal: 16,
    platform: "Viki",
    tags: ["Fantasía", "Romance"],
    status: "visto",
    synopsis:
      "Un general inmortal, una novia del destino y un ángel de la muerte con amnesia. La estética es un póster andante.",
    critic: { score: "8.1", quote: "Excesiva, hermosa y consciente de las dos cosas" },
    ratings: { jero: 8, flor: 7, liz: 9 },
    comments: {
      jero: "La fotografía es una locura, el guion se estira.",
      flor: "Buena, pero le sobran tres episodios.",
      liz: "El ángel de la muerte merecía su propia serie.",
    },
    when: { jero: "hace 1 mes", flor: "hace 1 mes", liz: "hace 6 sem" },
  },
  {
    id: "chacha",
    title: "Hometown Cha-Cha-Cha",
    orig: "갯마을 차차차",
    year: 2021,
    kind: "Serie",
    ep: 10,
    epTotal: 16,
    platform: "Netflix",
    tags: ["Romance", "Pueblo"],
    status: "mirando",
    synopsis:
      "Una dentista de ciudad abre consultorio en un pueblo de mar donde todos opinan sobre todo. Confort absoluto.",
    critic: { score: "7.8", quote: "El equivalente televisivo de una sopa caliente" },
    ratings: { jero: 7, flor: 8, liz: 0 },
    comments: {
      jero: "Perfecta para mirar sin pensar. Voy por el 10.",
      flor: "Quiero mudarme a Gongjin.",
      liz: "Demasiado dulce para mí, la abandoné en el 3.",
    },
    when: { jero: "hace 2 días", flor: "hace 4 días", liz: "hace 3 sem" },
  },
  {
    id: "twentyfive",
    title: "Twenty-Five Twenty-One",
    orig: "스물다섯 스물하나",
    year: 2022,
    kind: "Serie",
    ep: 0,
    epTotal: 16,
    platform: "Netflix",
    tags: ["Coming of age"],
    status: "pendiente",
    synopsis:
      "Esgrima, crisis del 98 y un primer amor contado desde el futuro. Aviso: el final divide amistades.",
    critic: { score: "8.0", quote: "Luminosa hasta que decide no serlo" },
    ratings: { jero: 0, flor: 0, liz: 0 },
    comments: {
      jero: "Me avisaron del final. Igual la veo.",
      flor: "Próxima en la fila.",
      liz: "Si el final es lo que dicen, paso.",
    },
    when: { jero: "—", flor: "—", liz: "—" },
  },
  {
    id: "parasite",
    title: "Parasite",
    orig: "기생충",
    year: 2019,
    kind: "Película",
    ep: 0,
    epTotal: 0,
    platform: "Max",
    tags: ["Thriller", "Social"],
    status: "visto",
    synopsis:
      "Una familia se infiltra en la casa de otra. Bong Joon-ho maneja la escalera como si fuera un personaje más.",
    critic: { score: "9.5", quote: "Comedia negra perfecta que se vuelve tragedia sin avisar" },
    ratings: { jero: 10, flor: 10, liz: 9 },
    comments: {
      jero: "La escena del sótano me sigue despertando.",
      flor: "Cine, punto.",
      liz: "Casi diez. Le saco un punto por lo obvio del final.",
    },
    when: { jero: "hace 4 meses", flor: "hace 4 meses", liz: "hace 4 meses" },
  },
  {
    id: "decision",
    title: "Decision to Leave",
    orig: "헤어질 결심",
    year: 2022,
    kind: "Película",
    ep: 0,
    epTotal: 0,
    platform: "Mubi",
    tags: ["Noir", "Romance"],
    status: "pendiente",
    synopsis:
      "Un detective insomne y una sospechosa que traduce sus sentimientos con el celular. Park Chan-wook en modo elegante.",
    critic: { score: "8.9", quote: "El policial más romántico y el romance más policial del año" },
    ratings: { jero: 0, flor: 0, liz: 0 },
    comments: {
      jero: "La quiero ver en pantalla grande.",
      flor: "Me da fiaca lo lento, pero bueno.",
      liz: "Esta la pongo yo el viernes.",
    },
    when: { jero: "—", flor: "—", liz: "—" },
  },
  {
    id: "busan",
    title: "Train to Busan",
    orig: "부산행",
    year: 2016,
    kind: "Película",
    ep: 0,
    epTotal: 0,
    platform: "Netflix",
    tags: ["Zombies", "Acción"],
    status: "visto",
    synopsis:
      "Zombies en el KTX y un padre que aprende a ser padre a 300 km/h. Funciona igual de bien la séptima vez.",
    critic: { score: "8.2", quote: "Género puro con el corazón exactamente donde debe estar" },
    ratings: { jero: 7, flor: 0, liz: 8 },
    comments: {
      jero: "Muy buena, aunque el final es tramposo.",
      flor: "Los zombies no son lo mío, la dejé a los 20 minutos.",
      liz: "El señor del sindicato es un héroe nacional.",
    },
    when: { jero: "hace 5 meses", flor: "hace 5 meses", liz: "hace 5 meses" },
  },
];

export const DISCOVER: DiscoverItem[] = [
  {
    id: "lovely",
    title: "Lovely Runner",
    year: 2024,
    kind: "Serie",
    why: "Viaje en el tiempo + idol. Porque Flor puso 10 a Crash Landing on You.",
  },
  {
    id: "queen",
    title: "Queen of Tears",
    year: 2024,
    kind: "Serie",
    why: "Matrimonio en crisis y herencias. Melodrama del bueno para las tres.",
  },
  {
    id: "moving",
    title: "Moving",
    year: 2023,
    kind: "Serie",
    why: "Superpoderes y padres espías: lo más cerca de The Glory que le va a gustar a Liz.",
  },
  {
    id: "burning",
    title: "Burning",
    year: 2018,
    kind: "Película",
    why: "Si Parasite les voló la cabeza, esta la desarma en silencio.",
  },
  {
    id: "attorney",
    title: "Extraordinary Attorney Woo",
    year: 2022,
    kind: "Serie",
    why: "Liviana y de a un episodio por noche, como Hometown Cha-Cha-Cha.",
  },
];

export const STATUS: Record<string, StatusMeta> = {
  pendiente: { label: "Pendiente", dot: "rgba(236,234,240,.4)", line: "En la fila" },
  mirando: { label: "Mirando", dot: "#f0604a", line: "Mirando" },
  visto: { label: "Visto", dot: "#e2a44b", line: "Visto" },
};

export function kindColor(kind: string): string {
  return kind === "Película" ? "#d6849b" : "#e2a44b";
}
